src/chapters/docker.xml
Note that these locations do not actually exist yet. They can't exist until post-release, as the Docker images must contain only release builds.
=> GUACAMOLE-97: Point Docker documentation at new image locations.

src/chapters/guacamole-ext.xml
This change:
1. Adds new sections describing sharing profiles, their permissions, and their use with respect to active connections.
2. Corrects out-of-date documentation from before authentication was decoupled from data storage.
3. Adds much needed documentation covering the overall authentication process, including the way that multiple extensions are polled, the retrieval of data from multiple extensions, and the generation of the login prompt.
=> GUACAMOLE-88: Document screen sharing for extensions

src/chapters/docker.xml
This change required reorganizing/rewriting much of the Docker chapter. Things were previously described rather monolithically:
* MySQL + guacd Docker link
* PostgreSQL + guacd Docker link
* LDAP + guacd Docker link
This is convenient in the sense that it provides a set of discrete sections with steps that can be followed more-or-less robotically, but it also duplicates configuration details common to each.
Because [GUACAMOLE-99](https://issues.apache.org/jira/browse/GUACAMOLE-99) adds support for using `GUACD_HOSTNAME` and `GUACD_PORT` instead of a Docker link, I was faced with the nauseating prospect of doubling what was already duplicated. I don't like doing work that is O(2^n), and chose to restructure things instead:
* guacd (link or environment variables)
* MySQL
* PostgreSQL
* LDAP …
=> GUACAMOLE-99: Document new GUACD_HOSTNAME and GUACD_PORT variables.

src/chapters/jdbc-auth.xml
There is no default any longer (see apache/incubator-guacamole-client#106).
=> GUACAMOLE-163: Remove description of default for password_date column.

src/chapters/custom-auth.xml, src/chapters/duo-auth.xml, src/chapters/guacamole-ext.xml, src/chapters/header-auth.xml, src/chapters/installing.xml, src/chapters/jdbc-auth.xml, src/chapters/ldap-auth.xml, src/chapters/noauth.xml, src/chapters/yourown.xml, src/gug.xml, tutorials/guacamole-auth-tutorial/pom.xml, tutorials/guacamole-auth-tutorial/src/main/resources/guac-manifest.json, tutorials/guacamole-tutorial/pom.xml
This change bumps all version numbers referenced within the manual, with the exception of guacamole-common which is unchanged.
=> GUACAMOLE-225: Bump version numbers to 0.9.12-incubating where appropriate.

src/chapters/ldap-auth.xml
This adds documentation for the single parameter added to the client that allows for configuring when the LDAP connection follows (dereferences) aliases.
=> GUACAMOLE-244: Configuration of Dereferencing Aliases

src/chapters/configuring.xml
This change adds documentation for the parameters added in apache/incubator-guacamole-server#84.
=> GUACAMOLE-40: Document gateway and load balancing parameters for RDP.

src/chapters/cas-auth.xml, src/chapters/custom-auth.xml, src/chapters/duo-auth.xml, src/chapters/guacamole-ext.xml, src/chapters/header-auth.xml, src/chapters/installing.xml, src/chapters/jdbc-auth.xml, src/chapters/ldap-auth.xml, src/chapters/yourown.xml, src/gug.xml, tutorials/guacamole-auth-tutorial/pom.xml, tutorials/guacamole-tutorial/pom.xml
As the database auth documentation was expanding badly with each change to the schema (one new paragraph per version), I've also generalized the documentation for the update scripts, hopefully simplifying things.
=> GUACAMOLE-314: Bump version to 0.9.13-incubating.

src/chapters/installing.xml
Adds a little bit of clarifying language to the documentation to note that OpenSSL is required for SSH support.  This is already present in one section in the manual, but this adds to the section specific to building SSH support.
=> GUACAMOLE-328: OpenSSL Required for SSH Support

src/chapters/configuring.xml
Adding the new server-alive-interval parameter to the documentation for SSH connections.
=> GUACAMOLE-203: Update SSH documentation to include keepalive interval

src/chapters/installing.xml
On Ubuntu the libjpeg62-turbo-dev package is named libjpeg-turbo8-dev, the instructions don't make that clear, I'd like to update the documentation to reflect that distinction.
=> GUACAMOLE-357: Update Documentation for Ubuntu Specific Library

src/chapters/configuring.xml
Quick fix.  Going to suggest this makes it into 0.9.14-incubating release.
=> GUACAMOLE-427: Fix documentation on load-balance-info parameter.

src/chapters/event-listeners.xml, src/chapters/guacamole-ext.xml, src/gug.xml
Documentation for event listener support in a single commit, based from staging/0.9.14-incubating.
=> GUACAMOLE-406: add documentation for event listener extensions

src/chapters/jdbc-auth.xml
This PR adds the documentation for the SQL Server JDBC extensions to the database authentication page.
Wasn't able to reopen the old PR, so doing a new one, here.
=> GUACAMOLE-363: Add SQL Server documentation to database manual page.

src/chapters/ldap-auth.xml
The documentation for the `ldap-operation-timeout` property added via #67 (part of [GUACAMOLE-243](https://issues.apache.org/jira/browse/GUACAMOLE-243)) contains an incorrectly-nested `<para>` which was clearly meant to be part of the empty `<listitem>` within the same `<varlistentry>`:
https://github.com/apache/guacamole-manual/blob/eab8ae3da4655e6677d44a81ddad982feb28d03f/src/chapters/ldap-auth.xml#L428-L435
The `<para>` just needs to be moved within the `<listitem>`.
=> GUACAMOLE-243: Correct XML structure of "ldap-operation-timeout" property.

src/chapters/jdbc-auth.xml
This change adds documentation covering the schema of the new `guacamole_user_history` table added by apache/guacamole-client#220 for [GUACAMOLE-394](https://issues.apache.org/jira/browse/GUACAMOLE-394).
=> GUACAMOLE-394: Document schema of new guacamole_user_history table.

src/chapters/configuring.xml, src/chapters/jdbc-auth.xml
This change removes the documentation for the properties now being removed via apache/guacamole-client#239.
=> GUACAMOLE-494: Remove documentation for deprecated properties.

src/chapters/configuring.xml
Adds documentation for the caching parameters to the RDP Performance section in the Configuration Guacamole chapter.
=> GUACAMOLE-448: Document new caching parameters for RDP connections.

src/chapters/docker.xml
Document the newly-added GUACD_LOG_LEVEL environment variable.
=> GUACAMOLE-42: Document GUACD_LOG_LEVEL variable.

src/chapters/configuring.xml
Correct the link to the JIRA issue tracker on the configuration page.
=> GUACAMOLE-582: Correct link to Apache JIRA tracker.

src/chapters/configuring.xml
Adds documentation for the printer-name parameter for naming RDP redirected print devices.
=> GUACAMOLE-445: Add documentation for printer-name parameter.

src/chapters/configuring.xml
Document the new format of the color-scheme parameter with some examples, for SSH and Telnet connections.
=> GUACAMOLE-470: Document new color-scheme parameter format for SSH and Telnet

src/chapters/configuring.xml, src/chapters/ldap-auth.xml
This change updates the LDAP attribute parameter token documentation to note the new `LDAP_` prefix and removes the documentation which covered the generic `GUAC_ATTR_` tokens (which no longer exist).
=> GUACAMOLE-524: Document new format of custom LDAP parameter tokens.

src/chapters/adhoc-connections.xml, src/chapters/cas-auth.xml, src/chapters/configuring.xml, src/chapters/custom-auth.xml, src/chapters/duo-auth.xml, src/chapters/event-listeners.xml, src/chapters/guacamole-ext.xml, src/chapters/header-auth.xml, src/chapters/installing.xml, src/chapters/jdbc-auth.xml, src/chapters/ldap-auth.xml, src/chapters/openid-auth.xml, src/chapters/radius-auth.xml, src/chapters/yourown.xml, src/gug.xml, tutorials/guacamole-auth-tutorial/pom.xml, tutorials/guacamole-auth-tutorial/src/main/resources/guac-manifest.json, tutorials/guacamole-tutorial/pom.xml
These changes update the documentation to point to the 1.0.0 versions of everything, as well as update the example command output within the installation instructions to match what would be produced by the upcoming 1.0.0 release.
=> GUACAMOLE-570: Bump version numbers within documentation to 1.0.0.

src/chapters/adhoc-connections.xml
There are two XML validation errors within the recently-merged adhoc connection docs:
* An `<indexterm>` cannot have multiple `<secondary>` terms. There is `<tertiary>`, but that doesn't look like what's intended here. For multiple terms, multiple `<indexterm> are required. See http://www.sagehill.net/docbookxsl/GenerateIndex.html for examples showing this in practice.
* `<uri>` is not an allowed child of `<informalexample>`. `<para>` is, however.
=> GUACAMOLE-38: Correct XML validation errors in guacamole-auth-quickconnect documentation.

src/chapters/installing.xml
Fixes GUACAMOLE-639: Add installation of libtool-bin for Debian/Ubuntu
When building Apache Guacamole from source, libtool-bin is required on
Debian/Ubuntu systems. 
Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>
=> GUACAMOLE-639: Add installation of libtool

src/chapters/jdbc-auth.xml
These changes:
* Reorganize the database auth documentation to include SQL Server among the databases affected by database upgrades (as the user group changes will be the first schema changes for the SQL Server support)
* Update the schema documentation to include the new tables, changes to the columns of existing tables, etc. added/made as a result of the user group changes.
To make things easier to navigate, the reorganization includes separating the documentation into distinct sections for creating the initial database, upgrading an existing database, and granting access to the database for Guacamole, with database-specific subsections for these, rather than main database-specific sections with repeated create/upgrade/grant subsections.
=> GUACAMOLE-220: Update database documentation for user groups.

src/chapters/ldap-auth.xml
This adds documentation for the ldap-member-attribute property which was added to resolve [JIRA issue 593](https://issues.apache.org/jira/browse/GUACAMOLE-593) via [PR 308](https://github.com/apache/guacamole-client/pull/308).
=> GUACAMOLE-593: Add documentation for ldap-member-attribute

src/chapters/totp-auth.xml
Because we only should speak like that on Speak Like a Pirate Day.
=> GUACAMOLE-718: Correct slight grammatical error in TOTP chapter.

src/chapters/configuring.xml
Add some brief documentation describing Guacamole's support for the NONE authentication mechanism in SSH.
=> GUACAMOLE-547: Document support for SSH NONE authentication.

src/chapters/configuring.xml
Document the German (Swiss) keyboard layout setting for RDP.
=> GUACAMOLE-354: Document de-ch-qwertz layout for RDP.

src/chapters/configuring.xml
Updated documentation to include the new keyboard layout in configure section.
=> GUACAMOLE-837: Add RDP keymap for Hungarian keyboard layout

src/chapters/configuring.xml, src/chapters/protocol.xml, src/references/instructions/client/handshake/audio.xml, src/references/instructions/client/handshake/image.xml, src/references/instructions/client/handshake/size.xml, src/references/instructions/client/handshake/timezone.xml, src/references/instructions/client/handshake/video.xml, src/references/instructions/server/handshake/args.xml, src/references/protocol.xml
A few items covered by this pull request:
* Document the timezone parameters for SSH and RDP
* Rearrange SSH documentation to match how parameters are currently configured.
* Document the timezone portion of the handshake, along with some notes about how instructions can now be in arbitrary order during the handshake phase.
I'm sure it needs some work, particularly the protocol/handshake section.
=> GUACAMOLE-422: Document support for timezone handshake and parameter.

src/chapters/configuring.xml
Initial cut at some documentation for extension-specific tokens.
=> GUACAMOLE-579: Add documentation for CAS extension tokens.

src/chapters/configuring.xml
Adds the `username` parameter documentation for VNC connections.
=> GUACAMOLE-514: Add documentation for VNC username parameter.

src/chapters/configuring.xml
This adds some parameter token documentation for the LDAP extension to the same Parameter Tokens section.
=> GUACAMOLE-524: Document LDAP parameter tokens with other parameter tokens

src/chapters/configuring.xml, src/chapters/installing.xml, src/chapters/troubleshooting.xml
This change updates the manual with respect to the FreeRDP 2.x support added through apache/guacamole-server#243. In particular:
* Notes warning that a particular feature is unavailable in an older version of FreeRDP have been removed (as only FreeRDP 2.x or above is now supported).
* Build output, build requirements, and error messages have been updated to reflect changes in log messages made via apache/guacamole-server#243.
* The new "nla-ext" security mode has been added, and the documentation of existing security modes has been clarified or expanded.
* The default security mode has been updated from "rdp" to "any".
=> GUACAMOLE-249: Update documentation with respect to FreeRDP 2.x support.

src/chapters/totp-auth.xml
TOTP no longer requires self update permission for users, instead leveraging `getPrivileged()` to obtain temporary privileged access for storing user attributes.
=> GUACAMOLE-708: Update documentation regarding changes in TOTP prereqs.

src/chapters/docker.xml
GUACAMOLE-912: Guacamole Docker image does not support Docker Links for LDAP. Fixed logical error in documentation to clarify that Guacamole Docker image does not support Docker Links.
=> GUACAMOLE-912: Guacamole Docker image does not support Docker Links for LDAP

src/chapters/configuring.xml
This change documents the `exec-command` parameter introduced by apache/guacamole-server#301.
=> GUACAMOLE-1174: Document Kubernetes "exec-command" parameter.

src/radius-auth.md
Documentation for apache/guacamole-client#586
=> GUACAMOLE-1252: Add documentation for specifying NAS IP.

src/cas-auth.md, src/conf.py, src/include/sso-download.md, src/include/sso-login-behavior.md, src/openid-auth.md, src/saml-auth.md
This change:
* Documents the new SSO extension structure adopted as of 1.4.0.
* Describes how SSO extensions behave when they have priority vs. when they don't, as well as how to change that priority to achieve the desired behavior.
=> GUACAMOLE-1364: Document SSO extension structure and behavior.

src/configuring-guacamole.md
See apache/guacamole-server#357.
=> GUACAMOLE-478: Document "normalize-clipboard" parameter for RDP.

Makefile
Instead of using -path, pass paths as regular arguments.  This is POSIX-compatible.
Without this, the `find` call fails on Mac OSX 10.15:
find: illegal option -- p
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
=> GUACAMOLE-1501: Makefile: use `find` in a POSIX-compatible way.

src/guacamole-docker.md
This change builds off the changes proposed by #130, addressing the PR feedback noted thus far and documenting the sole required variable: `REMOTE_IP_VALVE_ENABLED`.
This closes #130.
=> GUACAMOLE-1005: Document Docker configuration of RemoteIpValve.

src/guacamole-docker.md
This provides the documentation within the Docker section of the manual for configuring SAML authentication.
=> GUACAMOLE-1322: Provide documentation for configuring SAML authentication in the Docker container.

src/guacamole-protocol.md, src/protocol-reference.rst
This PR documents the protocol changes that were made when implementing the notification of connection join and leave events, notably the changes to the client -> server handshake, and the msg instruction.
=> GUACAMOLE-1293: Document protocol changes associated with sending messages to the client.

src/jdbc-auth.md
The properties do the same thing for each database, so I just copied the same documentation for each. Not sure if there's a better way.
=> GUACAMOLE-1723: Add documentation for access window enforcement for active sessions.

.github/workflows/pr-build.yml
Add PR verification job to guacamole-manual. See discussion on the equivalent client PR for more: https://github.com/apache/guacamole-client/pull/811.
=> GUACAMOLE-1754: Run docker build for PR CI.

src/guacamole-docker.md
This change documents the new Docker environment variable names related PostgreSQL, as well as the `--postgresql` option of `initdb.sh`, as implemented via:
* apache/guacamole-client#717 (original PR against `master`)
* apache/guacamole-client#860 (recreated PR against `staging/1.5.2`)
=> GUACAMOLE-1572: Document renamed POSTGRESQL_* variables and --postgresql option.

src/jdbc-auth.md
This change reapplies the same commits from #200 against `staging/1.5.2`.
=> GUACAMOLE-1727: Fix link to PostgreSQL JDBC downloads.

src/protocol-reference.rst
The [old page](https://web.archive.org/web/20120729032231/http://www.x.org/wiki/KeySyms) that it used to link to looked to be describing a change in how KeySyms worked, though it didn't have a lot of background. 
This [new page](https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#keysym_encoding) has more general information about KeySyms, including big tables of examples. It seems to me like this new page will be more helpful to reference here.
=> GUACAMOLE-1787: Link to an existing page that documents X11 KeySyms.

src/conf.py
This is required as of Sphinx 6.0 and the build now fails without this. Original warning from old versions of Sphinx was:
WARNING: extlinks: Sphinx-6.0 will require a caption string to
contain exactly one '%s' and all other '%' need to be escaped as
'%%'.
=> GUACAMOLE-1834: Include required '%s' for extlinks configuration.

src/guacamole-docker.md
Add documentation about the required and optional environment variables when using the TOTP extension with docker, similarly to how other authentication extensions are documented.
=> GUACAMOLE-1878: Add docker related TOTP autentication to documentation

src/reverse-proxy.md
This is a slight update to the `RemoteIpValve` documentation in the Proxy chapter of the manual that helps guide people in accounting for both IPv4 and IPv6 addresses, particularly loopback addresses.
=> GUACAMOLE-1861: Update RemoteIpValve documentation for both IPv4 and IPv6.

src/index.md
Noticed this issue when building other changes. Fixed now.
```
sphinx-build -b html -d build/doctrees src/ build/html
Running Sphinx v7.0.1
loading pickled environment... done
myst v4.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'colon_fence', 'smartquotes', 'substitution', 'replacements', 'deflist'}, disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_sort=True, footnote_transition=True, words_per_minute=200, substitutions={version: ...}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, …
```
=> GUACAMOLE-990: Fix auth-ban extension doc link in index.

src/auth-restrict.md
Just a few corrections and rewordings for the recently-merged documentation.
=> GUACAMOLE-1020: Grammatical corrections and clarifications for auth-restrict documentation.

src/cas-auth.md, src/configuring-guacamole.md, src/header-auth.md, src/jdbc-auth.md, src/json-auth.md, src/ldap-auth.md, src/openid-auth.md, src/radius-auth.md, src/saml-auth.md
This documents case-sensitivity settings for everything except the SSL SSO module, which is still pending documentation...
=> GUACAMOLE-1239: Add documentation for configuring username case sensitivity.

src/configuring-guacamole.md
Not sure if there's anything else that needs to be added for the GUACAMOLE-377 changes, but figured I'd try to get a jump on at least documenting this parameter.
=> GUACAMOLE-377: Document the disable-gfx property.

src/json-auth.md.j2
Add final steps for authenticating with Guacamole after obtaining the base64 of encrypted and signed JSON
=> GUACAMOLE-2142: Improve JSON-AUTH Documentation
